service: acharya-prototype
provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: eu-west-1

functions:
  init:
    ecr:
      images:
        acharya-prototype:
          path: ./
    timeout: 30
    handler: AcharyaMeasuringPrototype.init
    package:
      include:
        - AcharyaMeasuringPrototype.py
        - Utlis.py
        - Models/best.pt
    events:
      - http: 
          path: /init 
          method: POST

  health:
    timeout: 30
    handler: AcharyaMeasuringPrototype.health
    package:
      include:
        - AcharyaMeasuringPrototype.py
    events:
      - http: 
          path: /health
          method: GET

plugins:
  - serverless-python-requirements
  - serverless-offline

custom:
  pythonRequirements:
    dockerizePip: true